[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirect rules
[[redirects]]
  from = "/waitlist"
  to = "/#waitlist"
  status = 301

[[redirects]]
  from = "/demo"
  to = "/#features"
  status = 301

# Form handling (replace with your backend)
[[redirects]]
  from = "/api/waitlist"
  to = "https://your-backend-url.com/api/waitlist"
  status = 200
  force = true
